homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('Hobi/', views.hobi, name='hobi'),
    path('Pengalaman/', views.pengalaman, name='pengalaman'),
    path('Contact/', views.contact, name='contact'),
]

story4/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'Profile.html')

def pengalaman(request):
    return render(request, 'Pengalaman.html')

def hobi(request):
    return render(request, 'Hobi.html')

def contact(request):
    return render(request, 'Contact.html')

homepage/templates/Contact.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kontak saya</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Kontak Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'homepage:profile' %}">Profil</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya<span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>
    

    <div class="section4">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <p></p>
                    <br>
                    <h1 class="font-profle" style="color: red;">Social Media</h1>
                </div>
            </div>
            <div class="row" style="margin-left: 7.5em;margin-bottom: 30em">
                <div class="col-md-4">
                    <a href="https://api.whatsapp.com/send?phone=6281212025741">                                        
                        <img class="rounded-circle hover" src="{% static 'whatsapp.png' %}" style="width: 50%;">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="https://www.instagram.com/alfred_prasetio/?hl=id">                                        
                        <img class="rounded-circle hover" src="{% static 'instagram.png' %}" style="width: 50%;">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="https://line.me/R/ti/p/alfred_prasetio">                                        
                        <img class="rounded-circle hover" src="{% static 'line.png' %}" style="width: 50%;">
                    </a>
                </div>
            </div>
        </div>        
    </div>

</body>
</html>

homepage/templates/Hobi.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hobi saya</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
</head>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Hobi Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:profile' %}">Profil</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link " href="{% url 'homepage:hobi' %}">Hobi<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
            </li>
          </ul>
        </div>
      </nav>
    
    <div class="section2">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <h1 class="font-profile">Gaming</h1>
                    <p></p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width: 50%; height: 50%; margin: auto;">
                         <div class="carousel-item active">
                           <img class="d-block w-100" src="{% static 'valorant.jpg' %}". alt="First slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5>Valorant</h5>
                          </div>
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'dota.jpg' %}" alt="Second slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5>DoTA 2</h5>
                          </div>                          
                        </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'genshin.png' %}" alt="Third slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5 style="color: black;">Genshin Impact</h5>
                          </div>                          
                        </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'among.jpg' %}" alt="Fourth slide">
                           <div class="carousel-caption d-none d-md-block">
                            <h5>Among Us</h5>
                          </div>                          
                        </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                         <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href='#carouselExampleControls' role="button" data-slide="next">
                         <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                        <p></p>
                </div>
            </div>
        </div>
        <div class="container">
          <div class="row">
              <div class="col-md-12" style="text-align: center;">
                  <h1 class="font-profile">Gaming adalah hobi saya sejak SMP. Saya mulai bermain game karena diajak oleh teman saya. Saya tertarik dengan game dan akhirnya saya hobi bermain game.</h1>
                  <p></p>
              </div>
          </div>
      </div>
    </div>

</body>
</html>

homepage/templates/Pengalaman.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pengalaman saya</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Pengalaman Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'homepage:profile' %}">Profil</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
            </li>
          </ul>
        </div>
      </nav>
    
      <div class="section3">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <h1 class="font-profile" style="color: black;">Fotografi</h1>
                    <p></p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width: 50%; height: 50%; margin: auto;">
                         <div class="carousel-item active">
                           <img class="d-block w-100" src="{% static 'img1.JPG' %}" alt="First slide">
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'img2.JPG' %}" alt="Second slide">
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'img3.JPG' %}" alt="Third slide">
                          </div>
                          <div class="carousel-item">
                           <img class="d-block w-100" src="{% static 'img4.JPG' %}" alt="Fourth slide">
                          </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                         <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                         <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                        <p></p>
                </div>
            </div>
        </div>
        
        </div>
    </div>
</body>
</html>

homepage/templates/Profile.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Profile</title>
    <!-- file CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree Serif" rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'Style.css' %}">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>

<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
        <a class="navbar-brand" href="#">Profil Alfred Prasetio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'homepage:profile' %}">Profil<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
            </li>
          </ul>
        </div>
      </nav>


    <div class="section1">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <h1 class="font-profile" style="color: black;">My Profile</h1>
                    <img class="image1"src="{% static 'alpred.JPG' %}">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <h4 class="font-profile"> Nama : Alfred Prasetio</h4>
                    <h4 class="font-profile"> NPM : 1906398894</h4>
                    <h4 class="font-profile"> Umur : 19 Tahun</h4>
                    <h4 class="font-profile"> Pendidikan Terakhir : Fasilkom - Universitas Indonesia</h4>
                    <h4 class="font-profile" style="margin-bottom: 3em"> Angkatan : 2019</h4>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12" style="text-align: center">
                        <table border="1" style="border:1px solid white;margin:auto;" >
                            <tr>
                                <th align="center" style="color: white;">Tingkat</th>
                                <th align="center" style="color: white;">Nama Sekolah</th>
                                <th align="center" style="color: white;">Tahun</th>
                            </tr>
                            <tr>
                                <td align="center" style="color: white;">SD</td>
                                <td align="center" style="color: white;">SD Marsudirini Bekasi</td>
                                <td align="center" style="color: white;">2007 - 2013</td>
                            </tr>
                            <tr>
                                <td align="center" style="color: white;">SMP</td>
                                <td align="center" style="color: white;">SMP Marsudirini Bekasi</td>
                                <td align="center" style="color: white;">2013 - 2016</td>
                            </tr>
                            <tr>
                                <td align="center" style="color: white;">SMA</td>
                                <td align="center" style="color: white;">SMAK Penabur Harapan Indah</td>
                                <td align="center" style="color: white;">2016 - 2019</td>
                            </tr>
                            <tr>
                                <td align="center" style="color: white;">Kuliah</td>
                                <td align="center" style="color: white;">Fasilkom Universitas Indonesia</td>
                                <td align="center" style="color: white;">2019 - Sekarang</td>
                            </tr>
                        </table>      
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>